version: 2.1
jobs:
  build:
    macos:
      xcode: 12.5.1
    steps:
      - add_ssh_keys:
        fingerprints:
          - ""
      - checkout # check out the code in the project directory
      - run: |
          echo "hello world"

